#!/usr/bin/env python3
"""
Geister Medizintechnik - Customized PDF Catalog Generator
==========================================================
Generates a customer-specific product catalog PDF by extracting
ORIGINAL catalog pages (with all images) and highlighting the
requested article numbers.

Usage:
    python3 geister_custom_catalog.py

The script will interactively ask for:
  - Customer name and company
  - Article numbers (from either catalog)

It then copies the relevant original catalog pages into a new PDF,
highlights the requested articles, and adds a branded cover page.

Requirements:
    pip install pypdf pdfplumber reportlab
"""

import os
import sys
import re
from datetime import datetime
from collections import OrderedDict

import pdfplumber
from pypdf import PdfReader, PdfWriter
from reportlab.lib.pagesizes import landscape
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor, white, Color
from reportlab.pdfgen import canvas as rl_canvas
from io import BytesIO

# ============================================================
# GEISTER CI/CD DESIGN CONSTANTS
# ============================================================
GEISTER_RED = HexColor("#B5121B")
GEISTER_DARK_RED = HexColor("#8C0E15")
GEISTER_GRAY = HexColor("#58585A")
GEISTER_LIGHT_GRAY = HexColor("#E8E8E8")
HIGHLIGHT_COLOR = Color(0.71, 0.07, 0.11, alpha=0.15)  # Semi-transparent red
HIGHLIGHT_BORDER = HexColor("#B5121B")

# ============================================================
# SCRIPT DIRECTORY
# ============================================================
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

def discover_catalog_files(directory=None):
    """
    Automatically discover all PDF catalog files in the script directory.
    Excludes any files generated by this script (Geister_Selection_*.pdf).
    """
    scan_dir = directory or SCRIPT_DIR
    catalogs = []
    for f in sorted(os.listdir(scan_dir)):
        if f.lower().endswith(".pdf") and not f.startswith("Geister_Selection_"):
            catalogs.append(os.path.join(scan_dir, f))
    return catalogs


CATALOG_FILES = discover_catalog_files()

# Article number regex
ART_PATTERN = re.compile(r'\b(\d{2}-\d{4}(?:\.\w+)?(?:/\w+)?)\b')


# ============================================================
# INDEX BUILDER - Scans PDFs to map articles to pages
# ============================================================
def build_article_index(catalog_files):
    """
    Scan all catalog PDFs and build an index:
    article_number -> [(pdf_path, page_index, catalog_name)]

    Also returns page dimensions for each PDF.
    """
    index = {}
    page_dims = {}

    for pdf_path in catalog_files:
        if not os.path.exists(pdf_path):
            print(f"  [!] Catalog not found: {pdf_path}")
            continue

        catalog_name = os.path.basename(pdf_path).replace(".pdf", "")

        with pdfplumber.open(pdf_path) as pdf:
            page_dims[pdf_path] = (pdf.pages[0].width, pdf.pages[0].height)

            for page_idx, page in enumerate(pdf.pages):
                text = page.extract_text() or ""
                found_articles = ART_PATTERN.findall(text)

                for art_no in set(found_articles):
                    if art_no not in index:
                        index[art_no] = []
                    # Avoid duplicate entries for same pdf+page
                    entry = (pdf_path, page_idx, catalog_name)
                    if entry not in index[art_no]:
                        index[art_no].append(entry)

    return index, page_dims


def find_article_positions(pdf_path, page_idx, article_no):
    """
    Find exact positions of an article number on a specific page.
    Returns list of (x0, top, x1, bottom) bounding boxes.
    """
    positions = []
    with pdfplumber.open(pdf_path) as pdf:
        page = pdf.pages[page_idx]
        words = page.extract_words()

        for w in words:
            text = w["text"].strip()
            # Exact match or starts-with match (e.g., "34-7286" in "34-7286.GB")
            if text == article_no:
                positions.append((
                    float(w["x0"]),
                    float(w["top"]),
                    float(w["x1"]),
                    float(w["bottom"])
                ))

    return positions


# ============================================================
# HIGHLIGHT OVERLAY CREATOR
# ============================================================
def create_page_overlay(page_width, page_height, positions,
                        new_page_num=None, source_catalog=None,
                        original_page_num=None):
    """
    Create a transparent PDF overlay with:
    - Highlight rectangles on article positions
    - New page number (top corner, covers original)
    - Source reference footer (catalog name + original page)

    Args:
        page_width, page_height: page dimensions in points
        positions: list of (x0, top, x1, bottom) from pdfplumber coords
        new_page_num: new page number for the combined document
        source_catalog: name of the source catalog file
        original_page_num: original page number in the source catalog

    Returns:
        PdfReader page with overlay content
    """
    buf = BytesIO()
    c = rl_canvas.Canvas(buf, pagesize=(page_width, page_height))

    # ---- Highlight article positions ----
    for (x0, top, x1, bottom) in positions:
        # pdfplumber uses top-down coords, PDF uses bottom-up
        pdf_y_bottom = page_height - bottom
        pdf_y_top = page_height - top
        rect_height = pdf_y_top - pdf_y_bottom

        padding_x = 3
        padding_y = 2

        # Semi-transparent highlight fill
        c.setFillColor(HIGHLIGHT_COLOR)
        c.setStrokeColor(HIGHLIGHT_BORDER)
        c.setLineWidth(1.5)
        c.roundRect(
            x0 - padding_x,
            pdf_y_bottom - padding_y,
            (x1 - x0) + 2 * padding_x,
            rect_height + 2 * padding_y,
            2,
            fill=1,
            stroke=1
        )

        # Small red arrow/marker to the left
        arrow_x = x0 - padding_x - 10
        arrow_y = pdf_y_bottom + rect_height / 2
        c.setFillColor(HIGHLIGHT_BORDER)
        c.setStrokeColor(HIGHLIGHT_BORDER)
        path = c.beginPath()
        path.moveTo(arrow_x, arrow_y + 4)
        path.lineTo(arrow_x + 6, arrow_y)
        path.lineTo(arrow_x, arrow_y - 4)
        path.close()
        c.drawPath(path, fill=1, stroke=0)

    # ---- New page number (top corners, covering originals) ----
    if new_page_num is not None:
        # White rectangles to fully cover original page numbers
        # Top-left area (generous size to cover any original number)
        c.setFillColor(white)
        c.rect(0, page_height - 22, 55, 22, fill=1, stroke=0)
        # Top-right area
        c.rect(page_width - 55, page_height - 22, 55, 22, fill=1, stroke=0)

        # Also cover second-row area (some pages have number indented)
        c.rect(20, page_height - 36, 40, 16, fill=1, stroke=0)
        c.rect(page_width - 60, page_height - 36, 60, 16, fill=1, stroke=0)

        # Draw new page number (top-left, same style as originals)
        c.setFillColor(GEISTER_GRAY)
        c.setFont("Helvetica", 8)
        c.drawString(12, page_height - 13, str(new_page_num))

    # ---- Source reference footer ----
    if source_catalog and original_page_num is not None:
        # Clean up catalog name for display
        display_name = source_catalog.replace("_", " ")
        # Remove file extension if present
        if display_name.lower().endswith(".pdf"):
            display_name = display_name[:-4]

        ref_text = f"Source: {display_name}  |  Original p. {original_page_num}"

        # Small white background strip at very bottom
        c.setFillColor(Color(1, 1, 1, alpha=0.85))
        c.rect(0, 0, page_width, 14, fill=1, stroke=0)

        # Red thin line above
        c.setStrokeColor(GEISTER_RED)
        c.setLineWidth(0.4)
        c.line(10, 14, page_width - 10, 14)

        # Reference text
        c.setFillColor(GEISTER_GRAY)
        c.setFont("Helvetica", 5.5)
        c.drawString(12, 4, ref_text)

        # New page number also on bottom-right for clarity
        if new_page_num is not None:
            c.drawRightString(page_width - 12, 4, f"Page {new_page_num}")

    c.save()
    buf.seek(0)
    overlay_reader = PdfReader(buf)
    return overlay_reader.pages[0]


# ============================================================
# COVER PAGE CREATOR
# ============================================================
def create_cover_page(page_width, page_height, customer_name, customer_company,
                      article_count, page_count):
    """Create a branded Geister cover page."""
    buf = BytesIO()
    c = rl_canvas.Canvas(buf, pagesize=(page_width, page_height))

    w, h = page_width, page_height

    # ---- Background elements ----

    # White base
    c.setFillColor(white)
    c.rect(0, 0, w, h, fill=1, stroke=0)

    # Light gray lower section
    c.setFillColor(HexColor("#F2F2F2"))
    c.rect(0, 0, w, h * 0.35, fill=1, stroke=0)

    # Red circle accent (top-right, partially clipped)
    c.setFillColor(GEISTER_RED)
    c.circle(w + 10, h - 60, 140, fill=1, stroke=0)

    # Gray circle accent (right-center)
    c.setFillColor(HexColor("#C8C8C8"))
    c.circle(w - 30, h * 0.30, 110, fill=1, stroke=0)

    # ---- Geister Logo (top-left) ----

    logo_x = 30
    logo_y = h - 75
    logo_w = 55
    logo_h = 55

    # Red square with rounded corners
    c.setFillColor(GEISTER_RED)
    c.roundRect(logo_x, logo_y, logo_w, logo_h, 3, fill=1, stroke=0)

    # White "G" inside the square - large serif italic
    c.setFillColor(white)
    c.setFont("Times-BoldItalic", 42)
    c.drawString(logo_x + 10, logo_y + 10, "G")

    # "GEISTER" text below logo
    c.setFillColor(GEISTER_RED)
    c.setFont("Helvetica", 7.5)
    c.drawString(logo_x, logo_y - 12, "G E I S T E R")

    # ---- Red accent line (like in original catalog headers) ----
    c.setFillColor(GEISTER_RED)
    c.rect(0, h * 0.60, w * 0.55, 2, fill=1, stroke=0)

    # ---- Main Title ----
    title_y = h * 0.52
    c.setFillColor(HexColor("#1A1A1A"))
    c.setFont("Helvetica-Bold", 38)
    c.drawString(30, title_y, "CUSTOM PRODUCT")
    c.drawString(30, title_y - 44, "SELECTION")

    # "HIGHLIGHT" subtitle
    c.setFillColor(GEISTER_GRAY)
    c.setFont("Helvetica", 11)
    c.drawString(30, title_y - 72, "H I G H L I G H T")

    # ---- Customer Info Box (below title, no overlap) ----
    box_x = 30
    box_y = h * 0.12
    box_w = 350
    box_h = 80

    # White box with red border
    c.setFillColor(white)
    c.setStrokeColor(GEISTER_RED)
    c.setLineWidth(1.2)
    c.roundRect(box_x, box_y, box_w, box_h, 4, fill=1, stroke=1)

    # "Prepared for:" label
    c.setFillColor(GEISTER_RED)
    c.setFont("Helvetica", 8)
    c.drawString(box_x + 12, box_y + box_h - 16, "Prepared for:")

    # Customer name (bold, larger)
    c.setFillColor(HexColor("#1A1A1A"))
    c.setFont("Helvetica-Bold", 18)
    c.drawString(box_x + 12, box_y + box_h - 38, customer_name)

    # Company name
    c.setFillColor(GEISTER_GRAY)
    c.setFont("Helvetica", 11)
    c.drawString(box_x + 12, box_y + 10, customer_company)

    # Date (right-aligned in box)
    date_str = datetime.now().strftime("%d.%m.%Y")
    c.drawRightString(box_x + box_w - 12, box_y + 10, date_str)

    # ---- Document info (article count) ----
    c.setFillColor(GEISTER_GRAY)
    c.setFont("Helvetica", 8)
    info_text = f"{article_count} article(s) | {page_count} catalog page(s)"
    c.drawString(box_x + 12, box_y - 14, info_text)

    # ---- Footer ----
    c.setFillColor(GEISTER_GRAY)
    c.setFont("Helvetica", 6.5)
    c.drawString(
        30, 18,
        "GEISTER MEDIZINTECHNIK GMBH  |  Föhrenstrasse 2  |  "
        "D-78532 Tuttlingen  |  Germany  |  www.geister.com"
    )

    # Small tagline
    c.setFont("Helvetica-Oblique", 7)
    c.drawRightString(w - 30, 18, "The better way to operate\u2122")

    c.save()
    buf.seek(0)
    return PdfReader(buf).pages[0]


# ============================================================
# BACK PAGE (Contact / Closing)
# ============================================================
def create_back_page(page_width, page_height):
    """Create the closing page matching original catalog style."""
    buf = BytesIO()
    c = rl_canvas.Canvas(buf, pagesize=(page_width, page_height))

    w, h = page_width, page_height

    # White background
    c.setFillColor(white)
    c.rect(0, 0, w, h, fill=1, stroke=0)

    # Light gray lower portion
    c.setFillColor(HexColor("#F5F5F5"))
    c.rect(0, 0, w, h * 0.35, fill=1, stroke=0)

    # Red header bar
    c.setFillColor(GEISTER_RED)
    c.rect(0, h - 22, w, 10, fill=1, stroke=0)

    # Centered content
    center_x = w / 2

    # Tagline
    c.setFillColor(GEISTER_GRAY)
    c.setFont("Helvetica-Oblique", 11)
    c.drawCentredString(center_x, h * 0.72, "The better way to operate\u2122")

    # GEISTER large text
    c.setFillColor(GEISTER_RED)
    c.setFont("Helvetica", 32)
    c.drawCentredString(center_x, h * 0.62, "G E I S T E R")
    # ® symbol
    c.setFont("Helvetica", 10)
    c.drawString(center_x + 115, h * 0.65, "\u00AE")

    # Company name
    c.setFillColor(HexColor("#1A1A1A"))
    c.setFont("Helvetica-Bold", 12)
    c.drawCentredString(center_x, h * 0.53, "GEISTER MEDIZINTECHNIK GMBH")

    # Address
    c.setFillColor(GEISTER_GRAY)
    c.setFont("Helvetica", 9.5)
    c.drawCentredString(center_x, h * 0.48,
                        "Föhrenstrasse 2  |  D-78532 Tuttlingen  |  Germany")
    c.drawCentredString(center_x, h * 0.44,
                        "+49 7461 / 966240  |  +49 7461 / 9662422")

    # Website in red
    c.setFillColor(GEISTER_RED)
    c.setFont("Helvetica-Bold", 10)
    c.drawCentredString(center_x, h * 0.39, "www.geister.com")

    # Footer disclaimer
    c.setFillColor(GEISTER_GRAY)
    c.setFont("Helvetica", 5.5)
    year = datetime.now().year
    c.drawCentredString(center_x, 20,
        f"\u00A9 Geister Medizintechnik GmbH {year}  |  All rights reserved.  |  "
        "Technical changes, which serve progress and misprint reserved.")

    c.save()
    buf.seek(0)
    return PdfReader(buf).pages[0]


# ============================================================
# MAIN PDF GENERATOR
# ============================================================
def generate_catalog(customer_name, customer_company, article_numbers,
                     output_path=None, catalog_files=None, cached_index=None):
    """
    Generate a customized catalog PDF.

    Process:
    1. Use cached article index (or build from source catalogs)
    2. Find which pages contain the requested articles
    3. Copy those original pages (with all images!) into a new PDF
    4. Add highlight overlays on the requested article numbers
    5. Add cover + closing pages

    Args:
        customer_name: Customer's name
        customer_company: Customer's company
        article_numbers: List of article number strings
        output_path: Optional output file path
        catalog_files: Optional list of catalog PDF paths
        cached_index: Optional pre-built article index dict {art_no: [(pdf_path, page_idx), ...]}

    Returns:
        Path to the generated PDF, or None on failure
    """
    if catalog_files is None:
        catalog_files = CATALOG_FILES

    if cached_index is not None:
        print("\n  Using cached article index...")
        index = cached_index
        page_dims = {}
    else:
        print("\n  Scanning catalogs...")
        index, page_dims = build_article_index(catalog_files)
    print(f"  Found {len(index)} unique articles in index.")

    # Resolve requested articles
    found_articles = OrderedDict()
    not_found = []

    for art_no in article_numbers:
        art_no = art_no.strip()
        if art_no in index:
            found_articles[art_no] = index[art_no]
        else:
            # Try case-insensitive or partial match
            matched = False
            for idx_art in index:
                if idx_art.upper() == art_no.upper():
                    found_articles[idx_art] = index[idx_art]
                    matched = True
                    break
            if not matched:
                not_found.append(art_no)

    if not_found:
        print(f"  [!] Not found in catalogs: {', '.join(not_found)}")

    if not found_articles:
        print("  [!] No valid articles found. Aborting.")
        return None

    # Determine which pages to include (deduplicate)
    # Each page should only appear once, even if multiple articles are on it
    # Track: (pdf_path, page_idx) -> set of article numbers to highlight
    pages_to_include = OrderedDict()

    for art_no, locations in found_articles.items():
        # Pick the best page for this article (prefer pages with tables/data)
        # Usually the page with the most article numbers = the data page
        best_location = locations[0]

        # If article appears on multiple pages, prefer pages > 1
        # (page 0 is usually the cover)
        for loc in locations:
            if loc[1] > 0:  # Prefer non-cover pages
                best_location = loc
                break

        key = (best_location[0], best_location[1])
        if key not in pages_to_include:
            pages_to_include[key] = set()
        pages_to_include[key].add(art_no)

    print(f"  Selected {len(found_articles)} articles on {len(pages_to_include)} catalog page(s).")

    # Get page dimensions from first page to include (or default)
    pw, ph = 680.315, 481.89  # Default A4 landscape in points
    if pages_to_include:
        first_key = list(pages_to_include.keys())[0]
        try:
            reader_tmp = PdfReader(first_key[0])
            p = reader_tmp.pages[first_key[1]]
            pw = float(p.mediabox.width)
            ph = float(p.mediabox.height)
        except Exception:
            pass
    elif page_dims:
        first_pdf = catalog_files[0] if catalog_files else None
        if first_pdf and first_pdf in page_dims:
            pw, ph = page_dims[first_pdf]

    # Build the output PDF
    writer = PdfWriter()

    # 1. Add cover page
    cover = create_cover_page(pw, ph, customer_name, customer_company,
                              len(found_articles), len(pages_to_include))
    writer.add_page(cover)

    # 2. Add original catalog pages with highlights + new page numbering
    current_page = 2  # Cover is page 1
    for (pdf_path, page_idx), highlight_articles in pages_to_include.items():
        reader = PdfReader(pdf_path)
        orig_page = reader.pages[page_idx]

        # Find positions of all articles to highlight on this page
        all_positions = []
        for art_no in highlight_articles:
            positions = find_article_positions(pdf_path, page_idx, art_no)
            all_positions.extend(positions)

        # Create overlay with highlights + new page number + source reference
        page_w = float(orig_page.mediabox.width)
        page_h = float(orig_page.mediabox.height)
        catalog_filename = os.path.basename(pdf_path)
        original_page = page_idx + 1  # 1-based

        overlay = create_page_overlay(
            page_w, page_h, all_positions,
            new_page_num=current_page,
            source_catalog=catalog_filename,
            original_page_num=original_page
        )
        orig_page.merge_page(overlay)

        writer.add_page(orig_page)

        arts_str = ", ".join(sorted(highlight_articles))
        print(f"  + p.{current_page}: {catalog_filename} (orig. p.{original_page}) -> {arts_str}")
        current_page += 1

    # 3. Add closing page
    back = create_back_page(pw, ph)
    writer.add_page(back)

    # Write output
    if not output_path:
        safe_name = re.sub(r'[^\w\s-]', '', customer_company or customer_name)
        safe_name = re.sub(r'\s+', '_', safe_name).strip('_')
        date_str = datetime.now().strftime("%Y%m%d")
        filename = f"Geister_Selection_{safe_name}_{date_str}.pdf"
        output_path = os.path.join(SCRIPT_DIR, filename)

    with open(output_path, "wb") as f:
        writer.write(f)

    print(f"\n{'='*60}")
    print(f"  PDF generated successfully!")
    print(f"  Output: {output_path}")
    print(f"  Articles: {len(found_articles)}")
    print(f"  Pages: {len(pages_to_include) + 2} (incl. cover + closing)")
    print(f"  Customer: {customer_name}, {customer_company}")
    print(f"{'='*60}")

    return output_path


# ============================================================
# INTERACTIVE CLI
# ============================================================
def interactive_mode():
    """Run the interactive article selection and PDF generation."""

    print("\n" + "=" * 60)
    print("  GEISTER MEDIZINTECHNIK")
    print("  Custom Product Catalog Generator")
    print("=" * 60)

    # Scan catalogs first
    print("\n  Scanning catalogs...")
    index, _ = build_article_index(CATALOG_FILES)
    all_articles = sorted(index.keys())
    print(f"  Found {len(all_articles)} articles in {len(CATALOG_FILES)} catalog(s).\n")

    # Customer info
    print("--- Customer Information ---")
    customer_name = input("  Customer name: ").strip()
    if not customer_name:
        customer_name = "Customer"

    customer_company = input("  Company: ").strip()
    if not customer_company:
        customer_company = ""

    # Article selection
    selected = []
    print("\n--- Article Selection ---")
    print("  Enter article numbers (e.g., 34-7286, 29-1000)")
    print("  Commands:")
    print("    'list'   - Show all available articles")
    print("    'search' - Search by keyword or partial number")
    print("    'done'   - Finish selection and generate PDF")
    print("    'clear'  - Clear current selection")
    print("    'show'   - Show current selection")
    print()

    while True:
        user_input = input("  Article / Command > ").strip()

        if not user_input:
            continue

        cmd = user_input.lower()

        if cmd == "done":
            if not selected:
                print("  [!] No articles selected. Add at least one.")
                continue
            break

        elif cmd == "list":
            print(f"\n  All available articles ({len(all_articles)}):")
            for art in all_articles:
                locs = index[art]
                catalog = os.path.basename(locs[0][0]).split("_")[0]
                pages = ", ".join([str(l[1] + 1) for l in locs])
                print(f"    {art:<18} ({catalog}, page {pages})")
            print()
            continue

        elif cmd == "clear":
            selected.clear()
            print("  [OK] Selection cleared.")
            continue

        elif cmd == "show":
            if not selected:
                print("  [i] No articles selected yet.")
            else:
                print(f"\n  Current selection ({len(selected)} articles):")
                for art in selected:
                    print(f"    {art}")
            print()
            continue

        elif cmd.startswith("search"):
            parts = cmd.split(maxsplit=1)
            query = parts[1] if len(parts) > 1 else input("  Search term: ").strip()
            query_upper = query.upper()
            results = [a for a in all_articles if query_upper in a.upper()]
            if results:
                print(f"\n  Found {len(results)} match(es):")
                for art in results:
                    print(f"    {art}")
                print()
            else:
                print(f"  [!] No results for '{query}'")
            continue

        # Try to match the input as an article number
        art_input = user_input.strip()

        # Exact match?
        if art_input in index:
            if art_input in selected:
                print(f"  [i] {art_input} already selected.")
            else:
                selected.append(art_input)
                print(f"  [+] Added: {art_input}")
            continue

        # Partial/fuzzy match
        matches = [a for a in all_articles if art_input.upper() in a.upper()]
        if not matches:
            print(f"  [!] '{art_input}' not found. Try 'list' or 'search'.")
            continue

        if len(matches) == 1:
            art = matches[0]
            if art in selected:
                print(f"  [i] {art} already selected.")
            else:
                selected.append(art)
                print(f"  [+] Added: {art}")
        else:
            print(f"\n  Multiple matches for '{art_input}':")
            for i, art in enumerate(matches, 1):
                sel_mark = " *" if art in selected else ""
                print(f"    {i}. {art}{sel_mark}")

            choice = input("  Select number(s), 'all', or Enter to skip: ").strip()
            if choice.lower() == "all":
                for art in matches:
                    if art not in selected:
                        selected.append(art)
                        print(f"  [+] Added: {art}")
            elif choice:
                try:
                    indices = [int(x.strip()) - 1 for x in choice.split(",")]
                    for idx in indices:
                        if 0 <= idx < len(matches):
                            art = matches[idx]
                            if art not in selected:
                                selected.append(art)
                                print(f"  [+] Added: {art}")
                except ValueError:
                    print("  [!] Invalid input.")

    # Generate
    print("\n--- Generating PDF ---")
    output = generate_catalog(customer_name, customer_company, selected)

    if output:
        print(f"\n  Done! Open the file: {output}")


# ============================================================
# MAIN
# ============================================================
if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--help":
        print(__doc__)
        print("\nScanning catalogs for available articles...")
        index, _ = build_article_index(CATALOG_FILES)
        print(f"\nAvailable articles ({len(index)}):")
        for art in sorted(index.keys()):
            locs = index[art]
            catalog = os.path.basename(locs[0][0]).split("_")[0]
            print(f"  {art:<18} ({catalog})")
    else:
        interactive_mode()
